---
- name: "Display the OSCAP content via a web server"
  hosts: all
  vars:
    # Never actually use this password!
    upassword: "$6$xyz$Fx9jExqhA5hJXZ6MqQBxu0iW0.4HSqXrmtR7QCp/pYIYnwDd2gcywA8NettroJPZWbPWIjaYbyGD/w9ItzFys/"
  become: yes
  tasks:
    - name: Create the user myork and add to the wheel group
      ansible.builtin.user:
        name: myork 
        groups: wheel
        create_home: yes
        shell: /bin/bash
        password: "{{ upassword }}" 