---
- name: "Display the OSCAP content via a web server"
  hosts: all
  vars:
    # Never actually use this password!
    upassword: "redhat123"
  become: yes
  tasks:
    - name: Create the user myork and add to the wheel group
      ansible.builtin.user:
        name: myork 
        groups: wheel
        create_home: yes
        shell: /bin/bash
        password: "{{ upassword | password_hash('sha512') }} " 