---
- name: "Create a non privileged service account "
  hosts: all
  vars:
    # Never actually use this password!
    # I don't put useful passwords in code, but to save anyone time, this hash is "redhat123".
    # Please, please overwrite this variable as an extra var in the job template.
    upassword: "$6$xyz$Fx9jExqhA5hJXZ6MqQBxu0iW0.4HSqXrmtR7QCp/pYIYnwDd2gcywA8NettroJPZWbPWIjaYbyGD/w9ItzFys/"
    uuser: "myork"
  become: yes
  tasks:
    - name: Create the user "{{ uuser }}" and add to the wheel group
      ansible.builtin.user:
        name: "{{ uuser }}"
        groups: wheel
        create_home: yes
        shell: /bin/bash
        password: "{{ upassword }}" 