---
- name: "Create credentials for the service account"
  hosts: all
  vars:
    # Never actually use this password!
    # I don't put useful passwords in code, but to save anyone time, this hash is "redhat123".
    # Please, please overwrite this variable as an extra var in the job template.
    uppassword: "redhat123"
    uuser: "myork"
  become: yes
  tasks:
    - name: Create the credentials for "{{ uuser }}" and add to the wheel group
      awx.awx.credential:
        name: "Service account {{ uuser }}"
        organization: Default
        state: present 
        credential_type: Machine
        inputs:
          username: "{{ uuser }}"
          password: "{{ uppassword }}"
       