---
- name: "Patch the RHEL operating system "
  hosts: all
  vars: 
    REBOOT_DELAY: 60
    REBOOT_TIMEOUT_DELAY: 600
  become: yes
  tasks:
    - name: patch all kernel packages
      ansible.builtin.package:
        name: "*kernel*"
        state: latest
    
    - name: Run the command shutdown -r now 
      ansible.builtin.shell: reboot
      async: 1
      poll: 0

    - name: Reboot the system
      ansible.builtin.wait_for_connection:
        delay: "{{ REBOOT_DELAY | default(60) }}"
        timeout: "{{ REBOOT_TIMEOUT_DELAY | default(600) }}"

    - name: patch all other packages
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Reboot the system 
      ansible.builtin.shell: reboot
      async: 1
      poll: 0

    - name: wait for the system to reboot for the second time 
      ansible.builtin.wait_for_connection:
        delay: "{{ REBOOT_DELAY | default(60) }} "
        timeout: "{{ REBOOT_TIMEOUT_DELAY | default(600) }}" 



